# Generated by Django 3.2.7 on 2021-09-09 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0002_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='now',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='now_floor_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='now',
            name='now_floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maze.user'),
        ),
    ]
