# Generated by Django 3.2.7 on 2021-09-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0004_auto_20210910_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='now',
            old_name='u_id',
            new_name='u',
        ),
    ]
