# Generated by Django 3.2.7 on 2021-09-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0005_rename_u_id_now_u'),
    ]

    operations = [
        migrations.AddField(
            model_name='now',
            name='now_door',
            field=models.IntegerField(null=True),
        ),
    ]
