# Generated by Django 3.2.7 on 2021-09-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maze', '0007_alter_now_u'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='now',
            name='now_door',
        ),
    ]
